#!/usr/bin/env node
// Builds what the app needs from brand/, the single source of truth for the brand (06 §11).
//
//   node packages/ui/scripts/brand.mjs                 regenerate packages/ui/src/generated/ (committed)
//   node packages/ui/scripts/brand.mjs --check         fail if the generated files are out of date
//   node packages/ui/scripts/brand.mjs --public <dir>  copy fonts, logos, avatars and app icons into
//                                                      <dir>, and write the two manifests and the
//                                                      service worker (apps/web runs this before
//                                                      dev and build; the output is not committed)
import { createHash } from 'node:crypto';
import { cpSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { hexOf, themes } from './tokens.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const brand = join(root, 'brand');
const generatedDir = join(root, 'packages/ui/src/generated');

// Icon SVGs are inlined, so only plain drawing elements and attributes are accepted.
const SVG_TAGS = new Set(['path', 'circle', 'rect', 'ellipse', 'line', 'polyline', 'polygon', 'g']);
const SVG_ATTRS = new Set([
  'd',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'width',
  'height',
  'points',
  'fill',
  'stroke-width',
  'stroke-dasharray',
  'stroke-linecap',
  'stroke-linejoin',
  'opacity',
]);

function iconBody(file) {
  const svg = readFileSync(join(brand, file), 'utf8').trim();
  const body = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
  for (const [, tag] of body.matchAll(/<([a-zA-Z]+)/g)) {
    if (!SVG_TAGS.has(tag)) throw new Error(`${file}: <${tag}> is not allowed in an icon`);
  }
  for (const [, attr] of body.matchAll(/\s([a-zA-Z:-]+)=/g)) {
    if (!SVG_ATTRS.has(attr))
      throw new Error(`${file}: attribute ${attr} is not allowed in an icon`);
  }
  if (/fill="(?!none|currentColor)/.test(body))
    throw new Error(`${file}: icons use currentColor only`);
  return body;
}

/** A string as a single-quoted TypeScript literal. */
const quoted = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

/**
 * The picker's groups (brand/icons/groups.json, D-70): each group's own icons, then the Lucide icons
 * whose category is the group's key. Every name must exist, and no icon may be in two groups.
 */
function iconGroups(index) {
  const { groups } = JSON.parse(readFileSync(join(brand, 'icons/groups.json'), 'utf8'));
  const names = new Set(index.map((i) => i.name));
  const keys = new Set(groups.map((g) => g.key));
  const placed = new Set();
  const out = groups.map((g) => {
    const lucide = index.filter((i) => i.file.startsWith('icons/lucide/') && i.category === g.key);
    const icons = [...g.own, ...lucide.map((i) => i.name)];
    for (const name of icons) {
      if (!names.has(name)) throw new Error(`groups.json: ${g.key} names unknown icon ${name}`);
      if (placed.has(name)) throw new Error(`groups.json: ${name} is in two groups`);
      placed.add(name);
    }
    return { key: g.key, label: g.label, icons };
  });
  for (const i of index) {
    if (i.file.startsWith('icons/lucide/') && !keys.has(i.category))
      throw new Error(`${i.name}: its group ${i.category} is not in groups.json`);
  }
  return out;
}

function generatedFiles() {
  const index = JSON.parse(readFileSync(join(brand, 'icons/index.json'), 'utf8'));
  const icons = index.map((i) => `  ${quoted(i.name)}: '${iconBody(i.file)}',`);
  const iconsTs = `// Generated by packages/ui/scripts/brand.mjs from brand/icons/index.json. Do not edit.
// Each icon's drawing; its words and picker group are in icon-index.ts, which the board never loads.
export const ICONS = {
${icons.join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as IconName[];
`;
  const entries = index.map(
    (i) =>
      `  ${quoted(i.name)}: { category: ${quoted(i.category)}, keywords: [${i.keywords.map(quoted).join(', ')}] },`,
  );
  const groups = iconGroups(index).map(
    (g) => `  {
    key: ${quoted(g.key)},
    label: ${quoted(g.label)},
    icons: [${g.icons.map(quoted).join(', ')}],
  },`,
  );
  const indexTs = `// Generated by packages/ui/scripts/brand.mjs from brand/icons/index.json and groups.json. Do not edit.
import type { IconName } from './icons';

/** Each icon's category and search words. */
export const ICON_INDEX: Record<IconName, { category: string; keywords: readonly string[] }> = {
${entries.join('\n')}
};

/** The icon picker's groups, in order (D-70). Icons in no group are the app's own controls. */
export const ICON_GROUPS: readonly { key: string; label: string; icons: readonly IconName[] }[] = [
${groups.join('\n')}
];
`;

  const css = readFileSync(join(brand, 'familywise-tokens.css'), 'utf8');
  const { day, evening } = themes(css);
  const colors = {
    primary: hexOf(day, '--primary'),
    dayBackground: hexOf(day, '--bg'),
    eveningBackground: hexOf(evening, '--bg'),
  };
  const colorsTs = `// Generated by packages/ui/scripts/brand.mjs from brand/familywise-tokens.css. Do not edit.
// For places that cannot read CSS variables: manifests and the browser theme color.
export const BRAND_COLORS = ${JSON.stringify(colors, null, 2).replace(/"/g, "'")} as const;
`;
  const tokensCss = `/* Generated by packages/ui/scripts/brand.mjs: a copy of brand/familywise-tokens.css. Do not edit. */\n${css}`;
  return {
    'icons.ts': iconsTs,
    'icon-index.ts': indexTs,
    'colors.ts': colorsTs,
    'tokens.css': tokensCss,
    colors,
  };
}

function writeGenerated(check) {
  const files = generatedFiles();
  mkdirSync(generatedDir, { recursive: true });
  const stale = [];
  for (const name of ['icons.ts', 'icon-index.ts', 'colors.ts', 'tokens.css']) {
    const path = join(generatedDir, name);
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      // not generated yet
    }
    if (current === files[name]) continue;
    if (check) stale.push(relative(root, path));
    else writeFileSync(path, files[name]);
  }
  if (stale.length) {
    console.error(`out of date: ${stale.join(', ')}. Run node packages/ui/scripts/brand.mjs`);
    process.exit(1);
  }
}

function writePublic(dir) {
  const out = resolve(dir);
  const { colors } = generatedFiles();
  for (const sub of ['brand', 'icons']) rmSync(join(out, sub), { recursive: true, force: true });

  cpSync(join(brand, 'fonts.css'), join(out, 'brand/fonts.css'));
  cpSync(join(brand, 'fonts'), join(out, 'brand/fonts'), { recursive: true });
  cpSync(join(brand, 'avatars'), join(out, 'brand/avatars'), { recursive: true });
  cpSync(join(brand, 'logo'), join(out, 'brand/logo'), {
    recursive: true,
    filter: (src) => !src.endsWith('.png'),
  });
  cpSync(join(brand, 'app-icons'), join(out, 'icons'), {
    recursive: true,
    filter: (src) => !/\.(html|webmanifest)$/.test(src),
  });

  const icons = JSON.parse(
    readFileSync(join(brand, 'app-icons/manifest.webmanifest'), 'utf8'),
  ).icons;
  const manifest = (fields) => JSON.stringify({ name: 'FamilyWise', ...fields, icons }, null, 2);
  writeFileSync(
    join(out, 'board.webmanifest'),
    manifest({
      id: '/board',
      short_name: 'FamilyWise Board',
      description: 'The family board for chores, rewards, and the week ahead.',
      start_url: '/board',
      scope: '/board',
      display: 'fullscreen',
      display_override: ['fullscreen', 'standalone'],
      orientation: 'landscape',
      background_color: colors.eveningBackground,
      theme_color: colors.primary,
    }),
  );
  writeFileSync(
    join(out, 'admin.webmanifest'),
    manifest({
      id: '/admin',
      short_name: 'FamilyWise',
      description: "Manage your family's chores, rewards, and calendar.",
      start_url: '/admin',
      scope: '/admin',
      display: 'standalone',
      orientation: 'any',
      background_color: colors.dayBackground,
      theme_color: colors.primary,
    }),
  );

  // The kiosk must render offline, so the service worker precaches the self-hosted fonts.
  const fonts = readdirSync(join(brand, 'fonts'))
    .filter((f) => f.endsWith('.woff2'))
    .sort();
  const precache = ['/brand/fonts.css', ...fonts.map((f) => `/brand/fonts/${f}`)];
  const hash = createHash('sha256');
  for (const f of ['fonts.css', ...fonts.map((f) => `fonts/${f}`)])
    hash.update(readFileSync(join(brand, f)));
  const sw = readFileSync(join(root, 'packages/ui/scripts/sw.template.js'), 'utf8')
    .replace('__CACHE__', `familywise-brand-${hash.digest('hex').slice(0, 12)}`)
    .replace('__PRECACHE__', JSON.stringify(precache));
  writeFileSync(join(out, 'sw.js'), sw);
  console.log(
    `brand assets written to ${relative(process.cwd(), out) || '.'} (${precache.length} precached)`,
  );
}

const args = process.argv.slice(2);
if (args[0] === '--public') writePublic(args[1] ?? 'public');
else writeGenerated(args[0] === '--check');
